theme: jekyll-theme-cayman
title: "Bruno Drugowick"
logo: "assets/img/Drugo_2019.jpg"
description: "Blog about stuff that I find interesting and some things about myself."
excerpt_separator: <!--more-->
show_downloads: false
show_links: true
google_analytics: UA-139595994-1
