name: Update Articles

on:
  schedule:
    - cron:  '30 23 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run script to get articles from dev.to
        run: |
          ./scripts/post_files_from_GET_json.sh
      
      - name: Check for modifications and commit to the repo
        run: |
          ./scripts/check_for_changes_and_commit.sh

